# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: SadnAp's Blog
subtitle: 'Chinese ADV MUG Otaku'
description: ''
keywords: SadnAp'sBlog
author: SadnAp
language: en
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: 'https://blog.sadnapma.cf'
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: mashiro
plugins:
 - hexo-generator-feed

 - hexo-tag-aplayer
 - hexo-image-caption
 - hexo-reference
 - hexo-spoiler





# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:SadnAp/sadnap.github.io.git
  branch: main



# feed Atom
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20

#aplay https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  script_dir: js                       # Public 目录下脚本目录路径，默认: 'assets/js'
  style_dir: css                       # Public 目录下样式目录路径，默认: 'assets/css'
  cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js                # 引用 APlayer.js 外部 CDN 地址 (默认不开启)
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css        # 引用 APlayer.css 外部 CDN 地址 (默认不开启)
  meting_cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js           # 引用 Meting.js 外部 CDN 地址 (默认不开启)
  asset_inject: true                            # 自动插入 Aplayer.js 与 Meting.js 资源脚本, 默认开启
  meting: true

#https://github.com/lete114/hexo-seo-autopush

# enable: 开启/关闭 推送
# cron: 执行时间周期
# count: 每次提交最新的10篇文章
# date: 更新时间(updated)|创建日期(created)
# https://github.com/lete114/hexo-seo-autopush.git
hexo_seo_autopush:
  cron: 0 4 * * *
  baidu:
    enable: false
    date: created
    count: 10
  bing:
    enable: true
    date: created
    count: 10
  google:
    enable: false
    date: created
    count: 10
    google_file: google_service_account.json # 谷歌服务账户

# add caption for iamges https://github.com/wayou/hexo-image-caption
image_caption:
  enable: true #false to disable
  class_name: #if you wanna customize the style for the caption,you can assign a class name, default is 'image-caption'

funding:
  service: ko-fi # string (required) The funding service, if 'custom', url is required
  url: 'https://example.com/' # string (required if service='custom'), your custom url
  icon_name: 'name' # string (required if service='custom'), the icon displayed for your service, it's take from simple-icons's pack
  username: 'sadnapma' # string (required) Your ko-fi username
  enable: true # bool (default: true) Specifies if enable this plugin
  text: 'Support Me on {ko-fi}' # string (default: undefined) If specified, overrides the default "Support Me on {service}" string

sitemap:
  path: sitemap.xml

  rel: false
  tags: true
  categories: true
